name: Build ThingsBoard App

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

# 必须添加权限，否则无法创建 Release
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0' 
          channel: 'stable'

      # 自动从 pubspec.yaml 提取版本号
      - name: Get Version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Detected Version: $VERSION"

      - name: Create configs.json
        run: echo '${{ secrets.THINGSBOARD_CONFIGS }}' > configs.json

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses || true

      - name: Install Android NDK
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;29.0.13113456"

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --no-tree-shake-icons --dart-define-from-file configs.json

      # 重命名 APK，方便识别版本
      - name: Rename and Prepare APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/ThingsBoard-v${{ env.APP_VERSION }}.apk

      # 步骤 B: 发布到 GitHub Releases (永久保存)
      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        with:
          tag_name: v${{ env.APP_VERSION }}-${{ github.run_number }}
          name: Release v${{ env.APP_VERSION }}
          draft: false
          prerelease: false
          files: |
            build/app/outputs/flutter-apk/ThingsBoard-v${{ env.APP_VERSION }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
