name: Build ThingsBoard App

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 允许手动点击按钮触发编译

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          # 根据 ThingsBoard 版本选择 Flutter 版本
          # 1.8.0 推荐 3.29.0; 1.6.0 推荐 3.24.4
          flutter-version: '3.29.0' 
          channel: 'stable'

      - name: Create configs.json
        run: echo '${{ secrets.THINGSBOARD_CONFIGS }}' > configs.json

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Android Bundle (AAB)
        run: flutter build appbundle --no-tree-shake-icons --dart-define-from-file configs.json

      - name: Build Android APK (Optional)
        run: flutter build apk --no-tree-shake-icons --dart-define-from-file configs.json

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: tbmobile-release-aab
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: tbmobile-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
